### PR TITLE
package build

### PR DESCRIPTION
**Pull request by tjebo**
Hi Gorka. Awesome work. I thought why not make a package out of this, even if it should only remain on GitHub, it would be much easier to share (CRAN is quite restrictive regarding functions that write on other people's hard drive, so this would be hard to get through). 

I slightly changed the architecture by outsourcing a few steps to smaller functions. I have added a section for Mac users - I am using Mac and the command line soffice doesn't work then. 

Also, there was a small bug when looking for "documentclass" string, so I have slightly changed that too. 

I have modified the source path for the javascript script - had to put it into the "inst" folder so it will be installed, and it then can be found with base::system.file and sourced hopefully platform independent (using file.path)

### CODE REVIEW

**Comment by gorkang** [comment]
Thanks a lot Tjebo!

It is a great idea to make it into a "Github" package. And thanks for making it work on macs too!

**Comment by gorkang** [comment]
Only one thing. Could you make the deleted example.Rmd into a vignette?

Using this in a Rmd document requires a couple extra steps, and I believe it is useful to have it there.

**Comment by tjebo** [comment]
Hey, glad you like it. Sure thing. Will do.

**Comment by gorkang** [comment]
Awesome! Thanks a lot. Make sure you pull before sending the vignette, I made a couple small changes.

**Pull request merged**
